healthcare/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
     path('accounts/', include('allauth.urls')),
     path('oauth/', include('social_django.urls', namespace='social')),

]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    

main/urls.py
from django.urls import include, path
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
  
    path('', views.index, name='index'),
    path('about/',views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('contact/', views.contact, name='contact'),

    path('selfassess/', views.selfassess, name='selfassess'),
  path('dashboard/', views.dashboard, name='dashboard'),
  path('staffdashboard/', views.staffdashboard, name='staffdashboard'),
   path('admindashboard/', views.admindashboard, name='admindashboard'),

  path('loginuser/', views.loginuser, name='loginuser'),
  path('registeruser/', views.registeruser, name='registeruser'),
  path('logoutuser/', views.logoutuser, name='logoutuser'),
  path('change_password/', views.change_password, name='change_password'),

  path('partners/',views.partners, name="partners"),
  path('patientdetail/<str:id>', views.patientdetail, name='patientdetail'),
  path('createpatient/', views.createpatient, name='createpatient'),
  path('editpatient/<str:id>', views.editpatient, name='editpatient'),

  path('deletepatient/<str:id>', views.deletepatient, name='deletepatient'),
  path('blog/',views.blog,name='blog'),
  path('createblog/',views.createblog,name='createblog'),
  path('updateblog/<str:id>',views.updateblog,name='updateblog'),
  path('deleteblog/<str:id>',views.deleteblog,name='deleteblog'),

  path('blogdetail/<str:id>',views.blogdetail,name='blogdetail'),
  path('like_post/<int:id>', views.like_post, name='like_post'),
  path('comment_post/', views.comment_post, name='comment_post'),
  path('forms/',views.forms,name='forms'),
  path('walletpay/<str:id>',views.walletpay,name='walletpay'),
   path('reset_password/', auth_views.PasswordResetView.as_view(template_name='main/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="main/password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="main/password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="main/password_reset_done.html"), name='password_reset_complete'),
    path('cancel/<str:id>',views.cancel, name="cancel"),
    path('complete_profile/', views.complete_profile, name='complete_profile'),
     path('complete_doctorprofile/', views.complete_doctorprofile, name='complete_doctorprofile'),
    path('update_doctorprofile/', views.update_doctorprofile, name='update_doctorprofile'),
    path('update_profile/', views.update_profile, name='update_profile'),

    path('update_profile_pic/', views.update_profile_pic, name='update_profile_pic'),
   path('update_phone/', views.update_phone, name='update_phone'),
   path('approval/',views.approval,name='approval'),
   path('seniorapproval/<str:id>',views.seniorapproval,name='seniorapproval'),

   path('expertapproval/<str:id>',views.expertapproval,name='expertapproval'),
  path('adddoctor/<str:id>',views.adddoctor,name='adddoctor'),
    path('choose/',views.choose,name='choose'),
     path('load_doctors/', views.load_doctors, name='load_doctors'),

   path('booking/',views.booking,name='booking'),
    path('bookmeet/<str:id>',views.bookmeet,name='bookmeet'),
     path('preview/',views.preview,name='preview'),
     path('app_charge/',views.app_charge,name='app_charge'),

    path('createschedule/',views.createschedule,name='createschedule'),
     path('reschedule/<str:id>',views.reschedule,name='reschedule'),
      path('deleteschedule/<str:id>',views.deleteschedule,name='deleteschedule'),
      path('createwallet/',views.createwallet,name='createwallet'),
      path('recharge/',views.recharge,name='recharge'),
      path('rechargewallet/',views.rechargewallet,name='rechargewallet'),

    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField


#############################################################################################################

class Profile(models.Model):
    ROLES =(('Patient','Patient'),('Doctor','Doctor'),('Senior Doctor','Senior Doctor'),('Health Expert','Health Expert'))
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    profile_pic = models.ImageField(default='def.jpg',upload_to="images",null=True, blank=True)
    user_role = models.CharField(max_length=30,choices=ROLES,default="Patient")
    phone = PhoneField(blank=True, help_text='Contact Phone Number')

    def __str__(self):
        return self.user.username

class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    balance = models.IntegerField(default=100)
    def __str__(self):
        return self.user.username

class Broad(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Narrow(models.Model):
	broad = models.ForeignKey(Broad, on_delete=models.CASCADE)
	name = models.CharField(max_length=100, default="Not Available", blank=True, null=True)

	def __str__(self):
		return self.name

class Country(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class State(models.Model):
	country = models.ForeignKey(Country, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name




class DoctorProfile(models.Model):
	SS = (('Pending','Pending'),('Approved','Approved'))
	profile = models.OneToOneField(Profile, on_delete=models.CASCADE) 
	broad = models.ForeignKey(Broad, on_delete=models.CASCADE) 
	narrow = models.ForeignKey(Narrow, on_delete=models.CASCADE)
	state = models.ForeignKey(State, on_delete=models.CASCADE)
	country = models.ForeignKey(Country, on_delete=models.CASCADE)
	experience = models.IntegerField()
	address = models.TextField()
	approval1 = models.CharField(max_length=50, choices=SS, default="Pending")
	approval2 = models.CharField(max_length=50, choices=SS, default="Pending")

	def __str__(self):
		return self.profile.user.username



#########################################################################################################


class Schedule(models.Model):
    STATUSES = (('Free','Free'),('Booked','Booked'))
    docprof = models.ForeignKey(DoctorProfile,on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    status = models.CharField(max_length=30,choices=STATUSES,default='Free')


class Booked(models.Model):
    timing = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    pname = models.CharField(max_length=200)
    payment_id = models.CharField(max_length=100,blank=True,null=True)
    

class Patient(models.Model):
	docprof = models.ForeignKey(DoctorProfile,on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	complaint = models.CharField(max_length=100)
	investigation = models.CharField(max_length=100)
	examination =  models.CharField(max_length=100)

	def __str__(self):
		return self.name

###########################################################################################################



class Doctor(models.Model):

    broad = models.ForeignKey(Broad, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name



class Appointment(models.Model):
    appt_id = models.CharField(max_length=50,default="C100000")
    broad = models.ForeignKey(Broad, on_delete=models.SET_NULL, null=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.doctor.name



class Category(models.Model):
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name




class Post(models.Model):
	author = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE)
	title = models.CharField(max_length=255)
	image = models.ImageField(default='21.jpg',upload_to="images",null=True, blank=True)
	body = models.TextField()
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	post_date = models.DateField(auto_now_add=True)
	likes = models.ManyToManyField(User, related_name='blog_posts')

	def total_likes(self):
		return self.likes.count()

	def __str__(self):
		return self.title

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	body = models.TextField()
	date = models.DateField(auto_now_add=True)

class Top(models.Model):
	featured = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="featured")
	post1 = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post1")
	post2 = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post2")
	post3 = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post3")
	post4 = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post4")

class Feedback(models.Model):
	email = models.CharField(max_length=100,blank=True,null=True)
	username = models.CharField(max_length=100,blank=True,null=True)
	emoji = models.CharField(max_length=100,blank=True,null=True)
	reply =models.CharField(max_length=500,blank=True,null=True)

class Contact(models.Model):
	email = models.CharField(max_length=100,blank=True,null=True)
	name = models.CharField(max_length=100,blank=True,null=True)
	phone = models.CharField(max_length=100,blank=True,null=True)
	query = models.CharField(max_length=500,blank=True,null=True)
	message = models.CharField(max_length=100,blank=True,null=True) 

main/forms.py
from main.models import *
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.forms import UserChangeForm

from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2',]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('user_role','profile_pic','phone')


class DoctorProfileForm(forms.ModelForm):
    class Meta:
        model = DoctorProfile
        fields = ('broad', 'narrow','experience','address','state','country')


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email', 'username')
        exclude = ()



class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['broad','doctor',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['doctor'].queryset = Doctor.objects.none()

        if 'broad' in self.data:
            try:
                broad_id = int(self.data.get('broad'))
                self.fields['doctor'].queryset = Doctor.objects.filter(broad_id=broad_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['doctor'].queryset = self.instance.broad.doctor_set.order_by('name')


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ('date','time',)
        exclude = ()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','image','category','body',)
        exclude = ()


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('name','complaint','investigation','examination',)
        exclude = ()

main/templates/main/base.html
{% load static %}


<!DOCTYPE HTML>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <link rel="stylesheet" href="{% static 'css/staffdashboard.css' %}">
    <title>Hello, world!</title>
    <style>

      #total-orders{
        background-color:  #4cb4c7;
      }
      #orders-delivered{
        background-color:  #2abecc;
      }
      #orders-pending{
        background-color:  #7CD1C0;
      }

          .fb {
  background-color: #3B5998;
  color: white;

}
.google {
  background-color: #dd4b39;
  color: white;
}


.my-custom-scrollbar {
position: relative;
height: 200px;
overflow: auto;
}
.table-wrapper-scroll-y {
display: block;
}
    </style>
  </head>
  <body>

    <!-------- NAVBAR ----------------------------------------------------------------------------------------------------->

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">MED!CO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'feedback' %}">Feedback</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Our Partners
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Hospitals</a>
          <a class="dropdown-item" href="#">Laboratories</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">NGOs</a>
        </div>
      </li>
      {% if user.is_authenticated %}

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dashboard' %}">Dashboard <span class="sr-only">(current)</span></a>
      </li>

      {% if user.profile.doctorprofile%}

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'staffdashboard' %}"> Staff Dashboard <span class="sr-only">(current)</span></a>
      </li>

      {% endif %}


      

      {% if user.is_superuser %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admindashboard' %}"> Admin Dashboard <span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      {% endif %}
      <li class="nav-item">
       <!--- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> --->
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      
       {% if user.is_authenticated %}
       <button class="btn btn-info my-2 my-sm-0" type="button" data-toggle="modal" data-target="#LogoutModal">LOGOUT</button>
       <a href="{% url 'change_password' %}" class="btn btn-link my-2 my-sm-0">Change Password</a>
       {% else %}
       <div class="btn-group btn-group-toggle" data-toggle="buttons">
  
 

      <button class="btn btn-info my-2 my-sm-0" type="button" data-toggle="modal" data-target="#LoginModal">LOGIN</button>
    
      <a class="btn btn-warning my-2 my-sm-0" type="button" href="{% url 'registeruser' %}">REGISTER</a>
      {% endif %}
</div>    
  </div>
</nav>

 

<!-- LoginModal -->
<div class="modal fade" id="LoginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        
        <h5 class="modal-title" id="LoginModalLabel">LOGIN</h5>
       
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="form-inline" method="POST" action ="{% url 'loginuser' %}">
          {% csrf_token %}
  <div class="form-group mb-2">
    <label for="username" class="sr-only">Username</label>
    <input type="text" class="form-control-plaintext" name="username" id="username" placeholder="Username">
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <label for="password" class="sr-only">Password</label>
    <input type="password" name="password" class="form-control-plaintext" id="password" placeholder="Password">
  </div>

  {{ form.errors }}

      </div>
       <a href="{% url 'reset_password' %}" class="btn btn-link">I Forgot my password!</button>
      <div class="modal-footer">
        <div class="mt-4">
          <div class="d-flex justify-content-center links">
                   <a href="{% url 'social:begin' 'facebook' %}" class="fb btn">
          <i class="fa fa-facebook fa-fw"></i> Sign Up with Facebook
         </a>
       
      
      &nbsp;&nbsp;&nbsp;


        <a href="{% url 'social:begin' 'google-oauth2' %}" class="google btn"><i class="fa fa-google fa-fw">
          </i>&nbsp;&nbsp; Sign Up with Gmail
        </a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        </div></div>

         

        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Log In!</button></div></div>
</form>        
      </div>
    </div>
  </div>
</div>



<!-- LogoutModal -->
<div class="modal fade" id="LogoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        
        <h5 class="modal-title" id="LogoutModalLabel">LOGOUT</h5>
       
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5>Are You Sure you want to Log Out ?</h5>
      </div>
      <div class="modal-footer">
     <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a type="submit" class="btn btn-danger" href="{% url 'logoutuser' %}">Yes,Log me Out!!</a>
           
      </div>
    </div>
  </div>
</div>




    <!----------- NAVBAR END -------------------------------------------------------------------------------------------------->




{% block content %}

{% endblock %}

<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
    </div>
    <div class="col-6 col-md">
      <h5>Services</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="{% url 'choose' %}">Book Meeting</a></li>
        <li><a class="text-muted" href="{% url 'selfassess' %}">Self Assess</a></li>
        <li><a class="text-muted" href="{% url 'blog' %}">Read Blog</a></li>
    
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Doctors</a></li>
        <li><a class="text-muted" href="#">Hospitals</a></li>
        <li><a class="text-muted" href="#">NGOs</a></li>
        
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Government</a></li>
        <li><a class="text-muted" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Connect With Us</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="{% url 'feedback' %}">Feedback</a></li>
        <li><a class="text-muted" href="{% url 'contact' %}">Contact Us</a></li>
       
      </ul>
    </div>
  
  <div class="col-12 col-md">
  <p></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</div>
  </div>
</footer>


   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
   
   
    $("#id_broad").change(function () {
        const url = $("#SearchDocForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const broadId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'broad_id': broadId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_doctor").html(data);  // replace the contents of the city input with the data that came from the server
                /*
                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);
                */
            }
        });

    });

  </script>

  </body>




</html>

main/templates/main/booking.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}




<div class="jumbotron">
<h2>Dr. {{docprof.profile.user.first_name}} {{docprof.profile.user.last_name}}</h2> <h5>({{docprof.broad}} Specialist)</h5>

<hr>



<table class="table table-striped">
  <tr>
    <th>DATE</th><th>TIME</th><th>STATUS</th>
  </tr>
  {% for t in schedule %}
  <tr>
    <td>{{t.date}}</td>
    <td>{{t.time}}</td>
    <td>{% if t.status == 'Free' %}<a class="btn btn-success" href="{% url 'bookmeet' t.id %}">{{t.status}}</a>{% else %}<a class="btn btn-danger">{{t.status}}</a>{% endif %}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

main/templates/main/change_password.html
{% extends 'main/base.html' %}


{% block content %}

<br><br><br><br><br>
<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">CHANGE PASSWORD</h3>
					<hr>
				</div>
				<div class="d-flex justify-content-center form_container">



						
						</div>

<form method="post">
  {% csrf_token %}

						<div class="input-group mb-3">
							<div class="input-group-append"><Label></Label><br>
								
							</div>

  {{ form.old_password}}</div>
  <div class="input-group mb-3">
							<div class="input-group-append"><Label></Label><br>
								
							</div>
  {{ form.new_password1 }}</div>
  <div class="input-group mb-3">
							<div class="input-group-append"><Label></Label><br>
								
							</div>
 {{ form.new_password2 }}</div>


		<div class="d-flex justify-content-center mt-3 login_container">
				 	
				   		
  <button type="submit" class="btn btn-outline-success" >Change My Password!</button></div>
</form>
	</div>
		</div>
	</div>

	   			<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		
		form_fields[4].placeholder='Enter Current Password...';
		form_fields[5].placeholder='Enter New Password...';
		form_fields[6].placeholder='Re-enter New Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
{% endblock %}

main/templates/main/choose.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}


{% block content %}


<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <h3 id="form-title">Book Appointment</h3>
        </div>
        <div class="d-flex justify-content-center form_container">

<form method="post" id="SearchDocForm" data-cities-url="{% url 'load_doctors' %}">
    {% csrf_token %}
    

    <div class="input-group mb-3">
              <div class="input-group-append"><Label></Label><br>
                
              </div>{{ form.broad|as_crispy_field }}
    </div>
    
    <div class="input-group mb-3">
              <div class="input-group-append"><Label></Label><br>
                
              </div>{{ form.doctor|as_crispy_field }}
    </div>
    </div>
    
    <div class="d-flex justify-content-center mt-3 login_container">
              <input class="btn btn-outline-success" type="submit" value="Submit Details">
              </div>
</form>

</div>
      </div>
    </div>
  </div>



<script>
   
   
    $("#id_broad").change(function () {
        const url = $("#SearchDocForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const broadId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'broad_id': broadId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_doctor").html(data);  // replace the contents of the city input with the data that came from the server
                /*
                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);
                */
            }
        });

    });

  </script>

{% endblock %}